@extends('tfc.web.new.template')

@section('content')

        <div class="tm-bottom-b-box tm-full-width  ">
            <div class="uk-container uk-container-center">
                <section id="tm-bottom-b" class="tm-bottom-b uk-grid" data-uk-grid-match="{target:'> div > .uk-panel'}" data-uk-grid-margin="">

                    <div class="uk-width-1-1 uk-row-first">
                        <div class="uk-panel">
                            <div class="our-history-wrap">
                                
                                
                                <div class="uk-container uk-container-center">
                                    <div class="uk-grid">
                                        <!-- This is the container of the content items -->
                                        <div class="uk-width-medium-10-10">
                                                    <h3 class="history-title">Nuestro <span>Reglamento</span></h3>
                                                    <div class="uk-accordion" data-uk-accordion="">

                                                        <h4 class="uk-accordion-title uk-active">CAPITULO 1. ORGANIZACI�N DEL TORNEO<span class="arrow"><i class="uk-icon-arrow-right"></i></span></h4>
                                                        <div aria-expanded="true" data-wrapper="true" role="list" style="height: auto; position: relative;">
                                                            <div class="uk-accordion-content uk-active">Articulo 1. Estructura de las zonas: Se definir� la estructura de las zonas as� como su desarrollo y definici�n, previo al inicio de cada torneo, lo cual constituir� un anexo al presente reglamento. 
                                                            <br>Articulo 2. Reglamento de partido: TFC adaptar� su reglamentaci�n a los reglamentos vigentes de A.F.A., F.I.F.A y la International Board salvo en las siguientes excepciones: - Cambios de jugadores: se podr�n realizar hasta un m�ximo de 5 cambios por partido. - Los tiempos de juego se dividir�n en 2 de 40 (cuarenta) minutos cada uno. Antes de dar comienzo al encuentro los equipos deber�n haber: - Firmado la planilla del encuentro - Abonado el arancel correspondiente - El �rbitro y fiscal son quienes determinan el horario de comienzo del partido una vez cumplidos con los requerimientos mencionados.
                                                            <br> Articulo 3. Ley Walk Over Aquel equipo que obtuviere A SU FAVOR la aplicaci�n de la Ley del Walk Over en un partido determinado, obtendr� 3 (tres) puntos por el encuentro, d�ndosele el partido por ganado con un resultado de 2 (dos) goles de diferencia a su favor. La aplicaci�n de la ley Walk Over tendr� incidencia sobre el resultado del partido para los equipos involucrados, pero no modificar� la tabla de goleadores. Aplicaci�n de la Ley del Walk Over por el Comit� de Disciplina: I) Si el resultado al momento de dar por terminado el partido estuviera empatado, el resultado ser� favorable en 2 a 0 al equipo beneficiado por la Ley del Walk Over. II) Si el resultado al momento de dar por terminado el partido fuera favorable para el equipo sancionado con la Ley del Walk Over, este resultado quedar� anulado y se le dar� el partido por perdido en 2 a 0. III) Si el resultado al momento de dar por terminado el partido fuera favorable al equipo beneficiado por la Ley del Walk Over por una diferencia m�nima de 3 goles, se respetara el mismo. IV) Si el resultado al momento de dar por terminado el partido fuera favorable al equipo beneficiado por la Ley del Walk Over por hasta 2 (dos) goles de diferencia, el resultado ser� modificado por 2 a 0. 
                                                            <br>Articulo 4. Modificaciones a la estructura de la zona. Abandono del torneo. En el caso de que uno o m�s equipos abandonaren el Torneo antes de la finalizaci�n del mismo y a partir del momento en que se conoce la decisi�n, se proceder� de la siguiente manera, tomando como referencia la cantidad de partidos jugados por el equipo: a) Si el equipo abandonico hubiera jugado menos de la mitad de los partidos del torneo, se modificar� el resultado de los partidos que haya jugado aplic�ndose la Ley del walk-over para todos los partidos que hubiera jugado y para los partidos subsiguientes. O bien podr� reemplazar al equipo saliente con un nuevo equipo, tomando este, el puntaje de dicho equipo. Esta decisi�n quedar� sujeta de acuerdo al criterio que adopte la Organizaci�n en cuanto al mejor desarrollo del torneo. b) Si el equipo hubiera jugado la mitad o m�s de los partidos del torneo, se aplicar� la Ley del walk-over para todos los partidos que resten jugar por El Equipo, no modific�ndose el resultado de los partidos jugados. Cabe destacar que TFC no reembolsar� en ning�n caso los montos abonados por adelantado del equipo que decide abandonar el torneo. Este concepto tambi�n se aplica cuando el Comit� de Disciplina de TFC decida expulsar un equipo del torneo por mala conducta o actos de indisciplina. </div>
                                                        </div>

                                                        <h4 class="uk-accordion-title">CAPITULO 2. NORMAS ADMINISTRATIVAS<span class="arrow"><i class="uk-icon-arrow-right"></i></span></h4>
                                                        <div aria-expanded="false" data-wrapper="true" role="list" style="overflow:hidden;height:0;position:relative;">
                                                            <div class="uk-accordion-content">Articulo 5. Listas de Buena Fe a) La lista de jugadores o "Lista de Buena Fe" podr� incluir hasta 25 (veinticinco) jugadores. Todos los jugadores deben registrarse en la pagina de TFC en forma individual para poder formar parte de un equipo. Una vez cerradas las listas (3ra fecha) el equipo podr� anotar en cancha un m�ximo de 2 jugadores invitados en caso de necesitarlo. Estos jugadores invitados pueden estar anotados en otros equipos siempre y cuando no pertenezcan a la misma categor�a. La responsabilidad sobre el comportamiento de estos "jugadores invitados" recaer� en el capit�n o en quien TFC considere responsable seg�n lo expresado. Estos "jugadores invitados" deber�n atenerse a lo previsto en este reglamento de juego, y si alguno de ellos fuere expulsado y/o mereciera una sanci�n de 2 o mas partidos de suspensi�n, el Equipo es el responsable y podr� ser� sancionado econ�micamente o con quita de puntos. Se podr�n eliminar jugadores de la Lista de Buena Fe enviando un mail a TFC con sus respectivos nombres. Durante el torneo los jugadores podr�n seguir registr�ndose siempre y cuando la Lista no supere los 25 nombres. b) Los jugadores anotados como invitados no ser�n incluidos autom�ticamente a la lista para futuros partidos. En consecuencia, seguir� jugando como invitado hasta tanto no se registre individualmente a trav�s de la web. 
                                                            <br><br>Articulo 6. Planillas de cancha: a) Los jugadores, titulares y/o suplentes de El Equipo deber�n consignar sus datos con nombre y apellido, D.N.I. y numero de camiseta que utilizar�n durante el encuentro, antes de comenzar el partido. Asimismo deber�n firmar la planilla corroborando que los datos son fehacientes. Cualquier error u omisi�n de datos en la planilla de juego no podr� ser utilizada como argumento v�lido para posibles reclamos frente al Comit� de Disciplina, ya que el llenado de esta es exclusiva responsabilidad de El Equipo. b) Todos los jugadores estar�n obligados a acreditar su identidad al Arbitro del encuentro o a quien acredite ser personal de la Organizaci�n cuando estos se lo requieran. Si al momento de ser requerida la documentaci�n el jugador no la tuviera en su poder, sera facultad del arbitro y/o del fiscal de campo habilitar o no al jugador. En caso de ser requerida posterior al partido si el jugador no presenta su documento, el arbitro dejara constancia en la planilla y el Comit� de Disciplina lo citara a presentarse personalmente en la sede administrativa de TFC. Si el jugador se negara a presentar su documentaci�n o a presentarse personalmente cuando fuere citado, se considerar� que esta incluido en la lista en forma antirreglamentaria y se proceder� a sancionar tanto al jugador, como as� tambi�n al Equipo aplicando la Ley Walk Over en su contra.
                                                            <br><br>Articulo 7. Documentaci�n: A solicitud del Delegado de un equipo (y el Arbitro deber� dar cumplimiento reglamentariamente a tal solicitud), se podr� verificar las credenciales de los jugadores oponentes, antes de iniciarse el encuentro, durante el descanso o a la finalizaci�n del mismo, quedando obligados los Delegados a no permitir que ning�n jugador abandone el recinto deportivo, sin la autorizaci�n del Arbitro. CUALQUIER NEGATIVA POR PARTE DE UNO DE LOS EQUIPOS CONTENDIENTES DE SOMETERSE A TAL REVISION, SERA REFLEJADA EN LA PLANILLA RESPECTIVA Y SERA CALIFICADA POR EL COMIT� DE DISCIPLINA COMO ALINEACION INDEBIDA.
                                                            <br><br>Articulo 8. Inclusi�n indebida de jugadores: a) Se aplicar� la Ley del Walk Over en contra del equipo infractor en todos los partidos en que se haya comprobado la inclusi�n indebida. b) Descuento de 1 (un) punto en la tabla de posiciones al equipo infractor. c) 1 a 4 partidos m�s a la pena impuesta si el jugador se encontraba suspendido. 
                                                            <br><br>Articulo 9. Asistencia y puntualidad Los horarios asignados para cada partido son los de INICIO del encuentro por lo que el equipo deber� presentarse con una antelaci�n suficiente para cumplir a tiempo con el inicio programado. La tolerancia m�xima ser� de 15 minutos bajo todo concepto. Transcurrido ese lapso el �rbitro del encuentro dar� por concluido el encuentro y el equipo presente obtendr� los puntos del encuentro por aplicaci�n de Ley Walk Over. En este caso el equipo ausente deber� abonar el importe una multa de $800 antes de la siguiente fecha. Semanalmente se publicaran los horarios de los encuentros en la web de TFC los d�as Martes. Una vez publicados no se realizar�n cambios a pedido de los equipos. Sin perjuicio de ello TFC se reserva a realizar cambios de horario y sede comunicandoselo a los equipos con una anterioridad. Aquellos equipos que no asistan al los encuentros programados sin aviso previo deberan abonar una multa de $800. Se entiende por previo aviso 24hs antes del horario programado para su partido. 
                                                            <br>Articulo 10. Fair Play: Toda tarjeta amarilla o tarjeta roja que EL EQUIPO obtuviere en el transcurso del campeonato se registrar� en una Tabla de Fair Play que ser� actualizada en el informe de cada fecha de juego. Aquel equipo que, una vez finalizado el campeonato, se encuentre ubicado en el ultimo puesto en esta tabla, tendr� su vacante para el siguiente torneo sujeta a disposici�n de LA ORGANIZACI�N y su permanencia depender� de lo que esta decidiere. 
                                                            <br><br>Articulo 11. Indumentaria Es obligaci�n de los equipos contar con un conjunto de camisetas numeradas e id�nticas en modelo y color y distribuidas para titulares y suplentes. TFC no se ver� obligado a proveer camisetas y/o pecheras a los equipos que por alg�n motivo no las tengan dado que eso es responsabilidad exclusiva del equipo. En este caso el equipo que no se presente con camisetas no podr� ingresar al campo de juego d�ndole el partido por perdido. De cualquier manera TFC seg�n, su disponibilidad en ese momento, podr� alquilarles pecheras o camisetas al equipo a un valor de $50. TFC proveer� pecheras sin cargo a un equipo en caso de que el color de las camisetas de los equipos a enfrentarse sea muy similar a juzgar por el criterio del �rbitro. Ademas : a) no esta permitido intercambiar camisetas: cada jugador debe tener la propia, caso contrario no podra ingresar al campo de juego. b) no se permitir� la utilizaci�n de relojes, accesorios y/o botines con tapones met�licos c) Es obligatorio el uso de canilleras de protecci�n para todos los jugadores y no se permitir� a ning�n jugador utilizar medias sin tobillo. 
                                                            <br><br>ARTICULO 12. NORMAS ADMINISTRATIVAS a) Los equipos deber�n cumplir con las fechas y forma de pago elegida previo al inicio del torneo. b) Cabe destacar que, los equipos que incurran en atraso y/o incumplimiento, deber�n abonar intereses acordes a los �ndices normales de mercado. b) Los equipos que incurran en incumplimiento de pago , ya sea por lo mencionado en el Art. 12�, o por deuda de otra �ndole (ll�mese Multas, Pagos incompletos, etc.) ser�n objeto de pena con igual sanci�n. </div>
                                                        </div>

                                                        <h4 class="uk-accordion-title">CAPITULO 3. NORMAS DISCIPLINARIAS<span class="arrow"><i class="uk-icon-arrow-right"></i></span></h4>
                                                        <div aria-expanded="false" data-wrapper="true" role="list" style="overflow:hidden;height:0;position:relative;">
                                                            <div class="uk-accordion-content">Los coordinadores de sede tendr�n la facultad y/o autoridad para sancionar actos de indisciplina de diversa �ndole. Los mismos no necesitar�n advertencia de un arbitro sino que podr�n actuar de oficio cuando la situaci�n as� lo requiera. Las normas disciplinarias tienen por objeto fundamental preservar al torneo dentro del esp�ritu del deporte amateur, seg�n lo expresado en la introducci�n al reglamento. Para lograrlo se encargar� de sancionar las faltas cometidas antes, durante o despu�s del partido por jugadores, espectadores y/o simpatizantes de los equipos, se hallen o no dentro del campo de juego. La aplicaci�n de las mismas queda a criterio del Comit� de Disciplina, salvo casos excepcionales en los cuales, por circunstancias a determinar por TFC, sea conveniente convocar a una asamblea de capitanes. Los actos de indisciplina se pueden enmarcar en tres campos diferenciados: 1. los que se cometen entre los jugadores; 2. los que involucran a jugadores con arbitro y/o �rbitros asistentes, 3. los que involucran a jugadores con el personal de la Organizaci�n; De acuerdo a la gravedad del acto y los antecedentes surgen los m�nimos y m�ximos de las sanciones. Las sanciones a jugadores por acci�n prohibida por las reglas del juego durante el desarrollo del partido se regir�n seg�n las disposiciones vigentes de la Asociaci�n del F�tbol Argentino, y quedar� a criterio del �rbitro del encuentro su aplicaci�n. El Jugador que infrinja las disposiciones contenidas en el Reglamento o incurra en actos de indisciplina y sea expulsado del campo de juego, quedar� autom�ticamente inhabilitado para actuar hasta tanto se expida TFC. Del fallo definitivo se descontar� la pena cumplida por esta suspensi�n autom�tica. 
                                                            <br><br>Articulo 12. Actos de indisciplina entre jugadores: Siendo los jugadores los part�cipes directos del juego, y dando por sentado que todos se hallan en condici�n de igualdad ante la autoridad, los m�nimos y m�ximos de las sanciones a tomar surgir�n de la gravedad del acto en s� mismo, de la intencionalidad, de los antecedentes de/los infractor/es y del principio de acci�n y reacci�n. A continuaci�n se detallan las sanciones ORIENTATIVAS previstas para los casos en que act�e el Comit� de Disciplina. TFC adhiere a las normativas dispuestas por la F.I.F.A. y adaptara las sanciones previstas por el Reglamento de Transgresiones y Penas de la Asociaci�n del F�tbol Argentino a sus torneos de la siguiente forma: A) Que agreda a otro jugador aplic�ndole golpe por cualquier medio: 2 a 6 fechas 1�) Pu�etazo: estando o no en juego la pelota entre ambos jugadores. 2�) Cachetazo: estando o no en juego la pelota entre ambos jugadores. 3�) Puntapi�: estando o no la pelota en disputa entre ambos jugadores. 4�) Rodillazo: estando o no en disputa la pelota entre ambos jugadores. 5�) Cabezazo: sin estar disputando la pelota el jugador que lo aplique. 6�) Tacazo: sin estar disputando la pelota el jugador que lo aplique. 7�) Codazo: estando o no en disputa la pelota el jugador que lo aplique. 8�) Plancha: que llegue a destino, aplicada estando o no en disputa la pelota entre ambos jugadores. 9�) Pisar intencionalmente al adversario, estando el juego detenido. 10�) Arrojar la pelota con las manos o pies en forma deliberada al adversario, golpe�ndolo en el cuerpo o en la cara. 11�) Derribe, embiste, empuje, de empellones o zamarree violentamente a otro jugador o lo agarre en forma agresiva del cuello, de los cabellos, etc. B) Que salivare en forma deliberada a otro jugador: 2 a 6 fechas C)Actitud antideportiva: 1 a 2 fechas D) Insulte, agravie, amenace u ofenda, se mofe o burle de palabra, gesto o actitud a un jugador adversario: 1 a 2 fechas E) Empujones, manoteos entre jugadores, intento de agresi�n f�sica: 1 a 4 fechas F) Juego brusco grave (incluye foul como �ltimo recurso) 1 a 4 fechas G) Agresi�n f�sica, golpes que llegan a destino (sin estar disputando el bal�n): 3 a 6 fechas H) Replique la agresi�n de que fuera objeto: 1 a 3 fechas I) Se niegue a retirase del campo de juego una vez expulsado y deba ser retirado por sus compa�eros y/o provoque la suspensi�n moment�nea del encuentro: 1 a 4 fechas J) Juego Brusco simple, expulsiones con doble amonestaci�n, protestar fallos: 1 fecha K) Reincidencia en casos anteriores: se suma 1 fecha a la sanci�n correspondiente L) Detener el bal�n con la mano para evitar un gol o cualquier otra sanci�n arbitral que el comit� considere no sancionable: Advertencia o suspensi�n 1 fecha.
                                                            <br><br> Articulo 13. Sanciones en caso de agresi�n grupal: Cuando dos o mas jugadores de El Equipo se vean involucrados en casos de agresi�n antes, durante o despu�s del encuentro, El Equipo ser� ser sancionado en su conjunto. Las penas previstas para estos casos contemplaran inhabilitaciones a cada jugador, y/o inhabilitaciones al plantel completo y/o descuento de puntos, y/o expulsi�n del campeonato a jugadores puntualmente, y/o expulsi�n del campeonato a El Equipo. Se deja constancia que el partido quedara suspendido en el momento que el arbitro as� lo disponga. Quedaran a criterio del Comit� de Disciplina los puntos en juego. En este caso se entender� que los jugadores involucrados son los que hayan sido identificados por el �rbitro y/o sus asistentes y/o por personal de la Organizaci�n independientemente de la participaci�n que hayan tenido en el hecho. 
                                                            <br><br>Articulo 14. Sanci�n por acumulaci�n de tarjetas amarillas TFC ha resuelto: 1. Establecer la cantidad de tarjetas amarillas acumulables en 4 (cuatro) para ruedas de campeonato. 2. Y 7 (siete) para una segunda suspensi�n. 2.1. Limpiar el registro de acumulaci�n de tarjetas luego de la fase inicial clasificatoria y asignar un m�ximo de 2 tarjetas amarillas para la fase final o eliminatoria. 3. Suspender por 1 (un) partido a aquel jugador que llegare al limite de acumulaci�n de tarjetas establecido. 4. En el caso de los jugadores inhabilitados, los mismos aparecen con su sanci�n los d�as Martes en internet (www.thefutbolcompany.com), adem�s pueden consultar en forma telef�nica a la organizaci�n acerca de las sanciones o solicitar un e-mail. Adicionalmente el jugador tendr� su nombre resaltado en la planilla de cancha mientras dure su inhabilitaci�n. Por tanto, al no poder alegar desconocimiento de la sanci�n, si el jugador es incluido indebidamente, el equipo perder� los puntos de ese partido y el jugador suspendido de acuerdo al reglamento. 5. Todo jugador expulsado recibir� al menos 1 fecha de suspensi�n independientemente si lo fue con roja directa o doble amonestaci�n. 
                                                            <br><br>Articulo 15. Actos de indisciplina hacia �rbitros y/o �rbitros asistentes. TFC adhiere a las normativas dispuestas por la F.I.F.A., A.F.A., e International Board y adaptara las sanciones previstas por el Reglamento de Transgresiones y Penas de la Asociaci�n del F�tbol Argentino a sus torneos de la siguiente forma: A) Suspensi�n por tiempo indeterminado al jugador que agreda al arbitro aplic�ndole golpe por cualquier medio, o lo derribe, embista, empuje, salivare en forma deliberada o zamarree violentamente con prop�sitos de agresi�n.- B) Suspensi�n de 3 a 10 fechas al jugador que, intente agredir, le arroje intencionalmente la pelota con manos o pies alcanzando a golpearlo o cualquier otro ataque que se realice con menos violencia que en los casos previstos en el art�culo anterior. C) Suspensi�n de 2 a 6 fechas al jugador que provoque de palabra o actitud al �rbitro, discuta en tono violento, ofenda o insulte, se mofe o burle de palabra, gesto, actitud, adem�n equ�voco, hacerle ademanes obscenos o injuriosos, manosearlo o tironearlo de la ropa o inferirle cualquier otro agravio. Si luego de expulsado por ofender, insultar, agraviar o amenazar al �rbitro, el jugador vuelve en una 2da oportunidad, inmediata o mediatamente a ofender al �rbitro, el m�nimo de la pena se aumentar� 1 fecha; si lo hace no s�lo inmediatamente sino nuevamente desde fuera de la cancha en una tercera oportunidad el m�nimo se aumentar� en 2 fechas. D) Suspensi�n de 1 a 3 fechas, al jugador que abandone la cancha originando la suspensi�n del partido o la abandone como acto de disconformidad con el fallo del �rbitro. E) Suspensi�n de 2 a 3 fechas, al jugador que se resista a cumplir la orden de expulsi�n de la cancha impartida por el �rbitro. Se entiende que hay resistencia, cuando el jugador tiene que se retirado por la autoridad fuera de la cancha, cuyo caso es el veedor o supervisor del partido, compa�eros o adversarios. Sin perjuicio de lo expuesto el o los jugadores que agredan f�sicamente a �rbitros o personal de la organizaci�n ser�n denunciados en ese momento a las autoridades policiales y se radicar� la denuncia pertinente en los juzgados correspondientes. 
                                                            <br><br>Articulo 16. Actos de indisciplina hacia personal de la Organizaci�n. El jugador que insulte, agravie, agreda o intente agredir f�sicamente a personal de la Organizaci�n llevar� sanci�n similar que en los casos del punto anterior y ser� expulsado del torneo. 
                                                            <br><br>Articulo 17. Actos de indisciplina de asistentes e invitados del equipo. La cantidad m�xima de invitados o asistentes del equipo ser� de 5 personas sin contar t�cnico y jugadores suplentes. En el caso que los jugadores suplentes , asistentes o t�cnico del equipo ingresen al campo de juego o manifiesten actitudes de violencia verbal cualquiera sea el motivo, el equipo en su conjunto ser� sancionado en su conjunto con quita de de 1 a 10 puntos, independientemente de las sanciones a los jugadores. Bajo ning�n concepto podr�n ingresar al campo de juego los simpatizantes, t�cnicos o jugadores suplentes. Aquellos que lo hicieren sin autorizaci�n ser�n sancionados con suspensiones de 1 a 6 fechas. En caso de no poder identificarlos la sanci�n recaer� sobre el capit�n del equipo. TFC se reserva el derecho de admisi�n de las personas invitadas por los equipos. Se entiende por personas invitadas del equipo a aquellos que TFC haya identificado como tales independientemente de que el equipo lo/s reconozca o no. Los mismos pueden ser suspendidos o expulsados, neg�ndoles el ingreso a los predios bajo apercibimiento al equipo y luego expulsi�n del equipo si as� no lo hiciere. </div>
                                                        </div>

                                                        <h4 class="uk-accordion-title">CAPITULO 4. NORMAS COMPLEMENTARIAS<span class="arrow"><i class="uk-icon-arrow-right"></i></span></h4>
                                                        <div aria-expanded="false" data-wrapper="true" role="list" style="overflow:hidden;height:0;position:relative;">
                                                            <div class="uk-accordion-content">Articulo 18. Medios de comunicaci�n entre el Equipo y TFC The Futbol Company publicar� luego de cada fecha de juego un "informe semanal" en el que consignar� toda la informaci�n de la ultima fecha jugada, como ser Tablas de Posiciones, Resultados de los partidos, Tabla de Fair Play, Jugadores Inhabilitados para jugar la pr�xima fecha (con nombre, apellido y equipo), Fallos del Comit� de Disciplina (con nombre y apellido de los jugadores e informes del incidente), resumen de faltas administrativas, y toda otra informaci�n relevante concerniente a la ultima fecha jugada o a las pr�ximas fechas de juego. Esta informaci�n se publicara en el web site TFC: www.thefutbolcompany.com Adicionalmente podr� ser enviado por e-mail si el equipo as� lo solicita. TFC presumir� que la informaci�n fue recibida correctamente por El Equipo, por lo que no admitir� reclamos de El Equipo argumentados en una real o supuesta falta de conocimiento de la informaci�n all� contenida. 
                                                            <br><br>Articulo 19. De los �rbitros y sus informes: � El Arbitro es la m�xima autoridad en el desarrollo de un encuentro y como tal ser� respetado por todos los actores, tomando para s� la responsabilidad que el encuentro se celebre dentro de los causes deportivos, en noble competencia. � Los �rbitros-Asistentes son los naturales sustitutos del Arbitro, y por lo tanto podr�n suplirlo en su ausencia, con todos los derechos y garant�as que le corresponden al Arbitro. � El �rbitro o �rbitro asistente deber� presenciar la firma de la Planilla Reglamentaria y deber� constatar la correcta identidad de los firmantes. � Elevar el informe de lo acontecido en el partido, que ser� entregado a la Organizaci�n. Este informe adem�s observara la conducta de jugadores, t�cnicos y parciales, dentro y fuera del campo de juego. � El informe del arbitro ser� el elemento necesario y mas importante que usar� el Comit� de Disciplina en sus decisiones. Adicionalmente el CD tomara como suplementario el informe de los veedores de campo o de cualquier persona designada por TFC a tal efecto. 
                                                            <br><br>Articulo 20. Descargos de los Jugadores: El jugador, por intermedio de su capit�n, dispone de 48 horas desde la culminaci�n del partido para realizar su descargo en forma escrita ante TFC o por e-mail a tfc@thefutbolcompany.com 
                                                            <br><br>Articulo 21. Apelaciones de fallos: La apelaci�n de los fallos del Comit� de Disciplina ser� enviada a TFC por carta, v�a fax, por correo, por e-mail, remitida y firmada por el capit�n del equipo, detallando los motivos de dicha apelaci�n, los atenuantes en los cuales se basa, como as� tambi�n los datos del partido en cuesti�n. El hecho de apelar un fallo no significa una autom�tica reducci�n o anulaci�n de la sanci�n impuesta, sino que es un pedido de revisi�n de la pena corriendo por cuenta de TFC, a trav�s del Comit� de Disciplina, la medida a tomar en cada caso. La falta de respuesta por parte de TFC se entender� como respuesta negativa al pedido en cuesti�n. 
                                                            <br><br>Articulo 22. Recusaci�n e informes acerca de las actuaciones de los �rbitros: dice el articulo 170� del Reglamento General de la A.F.A.: "... Los clubes podr�n suministrar un informe sobre el desempe�o t�cnico del arbitro que act�e en cualquier partido en que intervengan sus equipos, calific�ndolo con alguno de los siguientes conceptos: bueno, regular o malo..." "... debiendo ser acompa�ado por las razones que, a su criterio motiven la calificaci�n y con referencias directas a las Reglas de Juego..." En este sentido TFC ha dispuesto, al contrario de lo expresado en el articulo 161� del Reglamento General de la A.F.A. que no permite a los equipos recusar a un �rbitro y solamente le permite elevar un informe de evaluaci�n que ser� tenido en cuenta para futuras designaciones y que cada equipo pueda efectuar una recusaci�n arbitral por a�o, la cual deber� ser presentada dentro de la semana en forma escrita y firmada por el capit�n y tendr� validez por el a�o en curso. No se admitir� reclamo alguno antes, durante o despu�s de un partido con respecto a la designaci�n de un arbitro si El Equipo no hubiere efectuado el pedido de recusaci�n formal. Este pedido ser� valido solo si es elevado por el capit�n del equipo. 
                                                            <br><br>Articulo 23. Asambleas Extraordinarias de Capitanes: Si excepcionalmente TFC decidiera someter un tema a la decisi�n de los equipos, podr� convocar a los equipos a emitir su opini�n y votar la determinaci�n a tomar. Los equipos deber�n estar representados por sus capitanes o, si esto no fuere posible, por alg�n jugador representativo designado por EL EQUIPO. El m�nimo de equipos representados para que la asamblea tenga validez ser� de 4 (cuatro), y las decisiones que all� se tomen resultar�n de una votaci�n, en donde cada equipo podr� emitir un solo voto (independientemente de la cantidad de representantes del equipo presentes en la reuni�n). El caso se decidir� por mayor�a de votos, en donde TFC tambi�n emitir� el suyo, el cual, en caso de escrutinio empatado, ser� el decisivo. 
                                                            <br><br>Articulo 25. Uso de las instalaciones y materiales de TFC: Rotura intencional y hurto: En caso de que un jugador o simpatizante rompiera intencionalmente material de TFC o instalaciones de los predios deportivos, ser� pasible de ser sancionado con 1 a 4 partidos de suspensi�n, y se cargar� el costo del mismo, o su reparaci�n a la cuenta de El Equipo. Si el hecho fuera protagonizado por un simpatizante de El Equipo, la suspensi�n recaer� sobre el capit�n. El hurto del material, tanto de los predios deportivos, como as� tambi�n de TFC, ser� penado de igual modo que la rotura intencional. Las instalaciones disponibles para la realizaci�n del torneo y/o partidos amistosos son las relativas para esta actividad: campos de juego, estacionamiento, vestuarios, bar. El resto de las instalaciones son de uso exclusivo de los afiliados y est�n restringidas para el uso de los jugadores e invitados a los encuentros. Dichas instalaciones comprenden: parrillas, quinchos, canchas relativas a otros deportes y actividades que no respondan a la realizaci�n del Torneo. Queda terminante prohibido orinar o cambiarse de ropa fuera de los vestuarios o ba�os dispuestos para tal fin . El jugador que sea identificado orinando fuera de los ba�os ser� informado al �rbitro y �ste lo expulsar� del encuentro ya sea antes, durante o despu�s del partido sin ninguna excepci�n. Aquellos que cometan dichas infracciones ser�n sancionadas con 1 fecha de suspensi�n. Sin perjuicio de ello las autoridades del club estar�n facultadas a retirar a la persona del club en ese momento. 
                                                            <br><br>Articulo 26. Suspensiones y postergaciones: En caso de duda sobre si se juega o no la fecha programada por cuestiones clim�ticas, el procedimiento a seguir ser� el siguiente: 1�) Si la fecha fuera suspendida de antemano por TFC, se le comunicar� a el equipo con anterioridad a la fecha de juego. 2�) Si existiera duda sobre la suspensi�n o no de la fecha de juego, el capit�n de El Equipo deber� confirmar en la pagina web si la fecha se juega. Dicha informaci�n estara disponible a partir de las 8.00am del mismo dia de partido, no antes. 3�) Toda fecha suspendida se recuperar� la semana siguiente, conserv�ndose el horario y la cancha asignada, salvo que TFC dispusiera una modificaci�n al respecto. 4�) Si una fecha debiera ser suspendida durante el transcurso de la misma, los partidos postergados se recuperaran en una fecha asignada a tal fin por TFC, preferentemente antes de la culminaci�n del torneo en curso. </div>
                                                        </div>

                                                    </div>
                                                </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>

@endsection
        
